### ISSUE TITLE
关于node的后端api

### ISSUE THREAD

**Issue by learnin-tap** [251205668/student-admin-template#1]
项目很棒哦，请问大佬考虑开源node写的后端吗？

**Comment by yzh990918** [comment]
后端部分只有socket服务是用node写的，其他的都是用springboot写的哦

**Comment by yzh990918** [comment]
@learnin-tap

**Comment by yzh990918** [comment]
[项目后端地址](https://github.com/251205668/student-admin) @learnin-tap

**Comment by learnin-tap** [comment]
![image](https://user-images.githubusercontent.com/52387803/86513807-bf4e0580-be3f-11ea-8019-5f10b514bbc1.png)
post请求调用接口失败 请问是什么地方填写错误吗

**Comment by learnin-tap** [comment]
好的谢谢大佬 我发现是我没带上 Content-Type 的值 打扰了

**Comment by yzh990918** [comment]
@learnin-tap 建议自己把后端克隆跑一下，这样传递参数就一目了然

**Comment by yzh990918** [comment]
或者可以看下这份[接口文档](https://documenter.getpostman.com/view/10611320/T17Ge7JB?version=latest) @learnin-tap

**Comment by learnin-tap** [comment]
非常感谢呀，还打算自己一个个写的呢
